# Generated by Django 4.1.1 on 2022-09-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancoApp', '0002_remove_customer_groups_remove_customer_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='email2',
        ),
    ]
