# Generated by Django 4.1.1 on 2022-09-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancoApp', '0005_rename_email2_customer_email_alter_usuario_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='no_cedula',
            new_name='id',
        ),
    ]
