# Generated by Django 4.1.1 on 2022-09-10 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancoApp', '0002_alter_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('no_cedula', models.BigIntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=255)),
                ('segundo_nombre', models.CharField(max_length=255)),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('no_celular', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(max_length=255)),
                ('ubicacion_gps_latitud', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ubicacion_gps_longitud', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=100)),
                ('no_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioMed', to='bancoApp.usuario')),
            ],
        ),
    ]
