# Generated by Django 4.1.1 on 2022-09-12 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancoApp', '0003_usuario_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='no_cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='bancoApp.usuario'),
        ),
    ]
