# Generated by Django 4.1.1 on 2022-09-12 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancoApp', '0004_alter_medico_no_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='enfermero',
            fields=[
                ('id_enfermero', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=100)),
                ('no_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioEnf', to='bancoApp.usuario')),
            ],
        ),
    ]
