# Generated by Django 4.1.1 on 2022-09-12 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancoApp', '0005_enfermero'),
    ]

    operations = [
        migrations.CreateModel(
            name='secretario',
            fields=[
                ('id_secretario', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(max_length=50)),
                ('no_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioSec', to='bancoApp.usuario')),
            ],
        ),
    ]
