# Generated by Django 4.1.1 on 2022-09-12 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancoApp', '0006_secretario'),
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('id_enfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermeroPac', to='bancoApp.enfermero')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoPac', to='bancoApp.medico')),
                ('no_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioPac', to='bancoApp.usuario')),
            ],
        ),
    ]
